services:
    newscoop_smarty_extensions_plugin.lifecyclesubscriber:
        class: Newscoop\SmartyExtensionsPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

